language: groovy

jdk:
  - oraclejdk8
  - openjdk7

script: "./gradlew build"

before_deploy:
  cp $TRAVIS_BUILD_DIR/build/libs/AnVerGen*.jar AnVerGen.jar

deploy:
  provider: releases
  skip_cleanup: true
  file: "AnVerGen.jar"
  api_key:
    secure: JJ8DSDOYVLz9xTAzlIXP6LJV8ZAcfJ6v/GT2webjD6rBJLeHqImKPMVCpagvp3taiW6rWjezoh99HpWIDxDZIfDZkeWVL70XDuq00+kQ9yYCDlxqDrD/1CksaPKWtlV373Bz3JxWDFsPrzMISA0HTPJWEmT9IfYIFU5uCjwWdoMeEY1HGq7z2rklOFZTUah4nuBHh3Ct6H950hTKZHGODeWqzyB3QqZKf18g37bwn2UYRQpyc/e2z5gqfp2YRz8Br1KWScEsk/iU3qMsvmv9F1M8dxIK8MT3dd33KkUrIvlnXiBwU8DNrk1NLWzZBbN/SotDa81yZvW5hWEYT9f2el98s3cRwXifikKdkcc/u0cxcc3c5PEAagym4OmcDMq++lkWGGBwUy6kzqDj4nhcdeb89kaLrBBxr2pfRu5l9VzJE5hL+qC4z8RqI0tU5QTPd4i6NFy2uBKSVN1pbPuEfGZtCTNe825JhbelluhjLXX4fAibDek3onyajE0D985rkvrWh5H/ZnrExH578D895onSJ5Keo2pCW2LGhcMYMaGdHI65r8RqBsZHbLDGOtLlFJ47reAAsy6fSCYppzi3pROQTRwkkvml/660vLi6WrgLtRQJv80UFn0k5DRGeT/oZf85srSZglC3KdJtTKjwV9h4a+X8qzCTcrURbQo7HfY=
  on:
    tags: true
    jdk: oraclejdk8

# vim: set shiftwidth=2 tabstop=2 softtabstop=-1 expandtab:
