language: groovy

jdk:
  - oraclejdk8
  - openjdk7

script: "./gradlew build"

after_success: export artifact=`ls $TRAVIS_BUILD_DIR/build/libs/AnVerGen*.jar`

before_deploy: echo $artifact

deploy:
  - provider: releases
    skip_cleanup: true
    file: $artifact
    api_key:
      secure: JJ8DSDOYVLz9xTAzlIXP6LJV8ZAcfJ6v/GT2webjD6rBJLeHqImKPMVCpagvp3taiW6rWjezoh99HpWIDxDZIfDZkeWVL70XDuq00+kQ9yYCDlxqDrD/1CksaPKWtlV373Bz3JxWDFsPrzMISA0HTPJWEmT9IfYIFU5uCjwWdoMeEY1HGq7z2rklOFZTUah4nuBHh3Ct6H950hTKZHGODeWqzyB3QqZKf18g37bwn2UYRQpyc/e2z5gqfp2YRz8Br1KWScEsk/iU3qMsvmv9F1M8dxIK8MT3dd33KkUrIvlnXiBwU8DNrk1NLWzZBbN/SotDa81yZvW5hWEYT9f2el98s3cRwXifikKdkcc/u0cxcc3c5PEAagym4OmcDMq++lkWGGBwUy6kzqDj4nhcdeb89kaLrBBxr2pfRu5l9VzJE5hL+qC4z8RqI0tU5QTPd4i6NFy2uBKSVN1pbPuEfGZtCTNe825JhbelluhjLXX4fAibDek3onyajE0D985rkvrWh5H/ZnrExH578D895onSJ5Keo2pCW2LGhcMYMaGdHI65r8RqBsZHbLDGOtLlFJ47reAAsy6fSCYppzi3pROQTRwkkvml/660vLi6WrgLtRQJv80UFn0k5DRGeT/oZf85srSZglC3KdJtTKjwV9h4a+X8qzCTcrURbQo7HfY=
    on:
      tags: true
      jdk: oraclejdk8
  - provider: bintray
    skip_cleanup: true
    file: ".descriptor.json"
    user: yanqd0
    on:
      tags: true
      jdk: oraclejdk8
    key:
      secure: uMXIrTbaCX1v0CLE5fNBDC+/2KaVUcuqjxnXaF/H2mt8b1UnrfFfqvZzr7qntjazUpj+/TeKaWhv+HiV893tIUNc3Lh1lrt/zPXi9m4shgT2DqI51BO6tyq280ttHZUf1Yhu6DGojzW9k5pSA3pB77/LdZP3I0Q4tufw1P4ZIb3YtWXR1iLzGck/J/gPBflLFVCkLIiVl68dXhkUf0g41odXVXWqnGpvYXZmT54KPwT1tTYchYFsaw7hOv5mzGHsj5f9/IfKFdK6pzJ6Dlb4OUoOaZqmv2ibWHLaslhLQDLNmdwz9JUaAfgW9/LPd4hZGFFEgVFG/cMLXXCBaSUje+Mx9bCF5UfAKSwIa8AO2b8M/DkfRuEMLlURVJ+2xuIjWZoHP8wTIUWLiI1PUPMA0wx4Fay5LGZZawPZuQHeqfnEsTfcXzepBgsByecyuQUoyiIbIf4GZupxCp3jhSqSwtCdJeUof8v8YIZE5lzV7/CSj9IKMUDVYKJDxJFGFvLuLde6zuUhLfa8J0YI0/86KgrDAuPbNW6OwHbWfccNb73FPrSgSuQYvzExPvDpmKryGbQZ85A2evTEXN5RhExDXJ6XVJK5Q3jPdbhjwRCucIziKae7FvPUH4+qIGo7t/yw2RDhKFZgE+xpUvj0fAv1WrUN7iH8c5XQN704kWIhnok=

after_script: echo $artifact

# vim: set shiftwidth=2 tabstop=2 softtabstop=-1 expandtab:
